config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#show", page: "home"

  # Handle Static pages
  get "/pages/*page" => "pages#show"

  resources :collections
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/collection.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: collections
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_collections_on_user_id  (user_id)
#
class Collection < ApplicationRecord
  belongs_to :user

  has_many :collection_records
  has_many :records, through: :collection_records

  validates :user_id, presence: true
end

app/models/collection_record.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: collection_records
#
#  id            :bigint           not null, primary key
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  collection_id :bigint           not null
#  record_id     :bigint           not null
#
# Indexes
#
#  index_collection_records_on_collection_id  (collection_id)
#  index_collection_records_on_record_id      (record_id)
#
class CollectionRecord < ApplicationRecord
  belongs_to :collection
  belongs_to :record

  validates :collection_id, :record_id, presence: true
end

app/models/organization.rb
# == Schema Information
#
# Table name: organizations
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Organization < ApplicationRecord
  has_many :organization_users
  has_many :users, through: :organization_users
end

app/models/organization_user.rb
# == Schema Information
#
# Table name: organization_users
#
#  id              :bigint           not null, primary key
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  organization_id :bigint
#  user_id         :bigint
#
# Indexes
#
#  index_organization_users_on_organization_id  (organization_id)
#  index_organization_users_on_user_id          (user_id)
#
class OrganizationUser < ApplicationRecord
  belongs_to :organization
  belongs_to :user
end

app/models/record.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: records
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_records_on_user_id  (user_id)
#
class Record < ApplicationRecord
  belongs_to :user

  has_many :collection_records
  has_many :collections, through: :collection_records

  validates :user_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :bigint           not null, primary key
#  confirmation_token :string(128)
#  email              :string           not null
#  encrypted_password :string(128)      not null
#  remember_token     :string(128)      not null
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
# Indexes
#
#  index_users_on_email           (email)
#  index_users_on_remember_token  (remember_token)
#
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[ show edit update destroy ]

  # GET /collections or /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1 or /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections or /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully created." }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1 or /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to collection_url(@collection), notice: "Collection was successfully updated." }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1 or /collections/1.json
  def destroy
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url, notice: "Collection was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collection_params
      params.fetch(:collection, {})
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def index
    @organizations = Organization.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    if valid_page?
      render template: "pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private

  def valid_page?
    File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection.html.erb
<div id="<%= dom_id collection %>">
  <% if action_name != "show" %>
    <%= link_to "Show this collection", collection, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this collection', edit_collection_path(collection), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/collections/_form.html.erb
<%= form_with(model: collection, class: "contents") do |form| %>
  <% if collection.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing collection</h1>

  <%= render "form", collection: @collection %>

  <%= link_to "Show this collection", @collection, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to collections", collections_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/collections/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Collections</h1>
    <%= link_to 'New collection', new_collection_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="collections" class="min-w-full">
    <%= render @collections %>
  </div>
</div>

app/views/collections/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New collection</h1>

  <%= render "form", collection: @collection %>

  <%= link_to 'Back to collections', collections_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/collections/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @collection %>

    <%= link_to 'Edit this collection', edit_collection_path(@collection), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this collection', collection_path(@collection), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to collections', collections_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magister</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "fonts", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"> <%= value %> </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/organizations/index.html.erb
<div class="flex flex-center container m-4 px-8">
  <ul>
    <% @organizations.each do |organization| %>
      <li>
        <div class="flex-col justify-items-stretch">
          <div class="flex-auto basis-3">
            <span class="font-4xl font-gothic"> <%= organization.name %></span>
          </div>
        </div>
      </li>
      <% end %>
  </ul>
</div>

app/views/pages/home.html.erb
<div class="container mx-auto px-4">
  <style type="text/css">
    @-webkit-keyframes spincube {
      from,to  { -webkit-transform: rotateX(0deg) rotateY(0deg) rotateZ(0deg); }
      16%      { -webkit-transform: rotateY(-90deg);                           }
      33%      { -webkit-transform: rotateY(-90deg) rotateZ(90deg);            }
      50%      { -webkit-transform: rotateY(-180deg) rotateZ(90deg);           }
      66%      { -webkit-transform: rotateY(-270deg) rotateX(90deg);           }
      83%      { -webkit-transform: rotateX(90deg);                            }
    }

    @keyframes spincube {
      from,to {
        -moz-transform: rotateX(0deg) rotateY(0deg) rotateZ(0deg);
        -ms-transform: rotateX(0deg) rotateY(0deg) rotateZ(0deg);
        transform: rotateX(0deg) rotateY(0deg) rotateZ(0deg);
      }
      16% {
        -moz-transform: rotateY(-90deg);
        -ms-transform: rotateY(-90deg);
        transform: rotateY(-90deg);
      }
      33% {
        -moz-transform: rotateY(-90deg) rotateZ(90deg);
        -ms-transform: rotateY(-90deg) rotateZ(90deg);
        transform: rotateY(-90deg) rotateZ(90deg);
      }
      50% {
        -moz-transform: rotateY(-180deg) rotateZ(90deg);
        -ms-transform: rotateY(-180deg) rotateZ(90deg);
        transform: rotateY(-180deg) rotateZ(90deg);
      }
      66% {
        -moz-transform: rotateY(-270deg) rotateX(90deg);
        -ms-transform: rotateY(-270deg) rotateX(90deg);
        transform: rotateY(-270deg) rotateX(90deg);
      }
      83% {
        -moz-transform: rotateX(90deg);
        -ms-transform: rotateX(90deg);
        transform: rotateX(90deg);
      }
    }

    .cubespinner {
      -webkit-animation-name: spincube;
      -webkit-animation-timing-function: ease-in-out;
      -webkit-animation-iteration-count: infinite;
      -webkit-animation-duration: 18s;

      animation-name: spincube;
      animation-timing-function: ease-in-out;
      animation-iteration-count: infinite;
      animation-duration: 18s;

      -webkit-transform-style: preserve-3d;
      -moz-transform-style: preserve-3d;
      -ms-transform-style: preserve-3d;
      transform-style: preserve-3d;

      -webkit-transform-origin: 60px 60px 0;
      -moz-transform-origin: 60px 60px 0;
      -ms-transform-origin: 60px 60px 0;
      transform-origin: 60px 60px 0;
    }

    .cubespinner div {
      position: absolute;
      width: 360px;
      height: 360px;
      border: 1px solid #ccc;
      background: rgba(255,255,255,0.8);
      box-shadow: inset 0 0 20px rgba(0,0,0,0.2);
      line-height: 360px;
      text-align: center;
      font-size: 120px;
    }

    .cubespinner .face1 {
      -webkit-transform: translateZ(180px);
      -moz-transform: translateZ(180px);
      -ms-transform: translateZ(180px);
      transform: translateZ(180px);
    }
    .cubespinner .face2 {
      -webkit-transform: rotateY(90deg) translateZ(180px);
      -moz-transform: rotateY(90deg) translateZ(180px);
      -ms-transform: rotateY(90deg) translateZ(180px);
      transform: rotateY(90deg) translateZ(180px);
    }
    .cubespinner .face3 {
      -webkit-transform: rotateY(90deg) rotateX(90deg) translateZ(180px);
      -moz-transform: rotateY(90deg) rotateX(90deg) translateZ(180px);
      -ms-transform: rotateY(90deg) rotateX(90deg) translateZ(180px);
      transform: rotateY(90deg) rotateX(90deg) translateZ(180px);
    }
    .cubespinner .face4 {
      -webkit-transform: rotateY(180deg) rotateZ(90deg) translateZ(180px);
      -moz-transform: rotateY(180deg) rotateZ(90deg) translateZ(180px);
      -ms-transform: rotateY(180deg) rotateZ(90deg) translateZ(180px);
      transform: rotateY(180deg) rotateZ(90deg) translateZ(180px);
    }
    .cubespinner .face5 {
      -webkit-transform: rotateY(-90deg) rotateZ(90deg) translateZ(180px);
      -moz-transform: rotateY(-90deg) rotateZ(90deg) translateZ(180px);
      -ms-transform: rotateY(-90deg) rotateZ(90deg) translateZ(180px);
      transform: rotateY(-90deg) rotateZ(90deg) translateZ(180px);
    }
    .cubespinner .face6 {
      -webkit-transform: rotateX(-90deg) translateZ(180px);
      -moz-transform: rotateX(-90deg) translateZ(180px);
      -ms-transform: rotateX(-90deg) translateZ(180px);
      transform: rotateX(-90deg) translateZ(180px);
    }

    .font-gothic {
      font-family: "bu Gothic Hybrid"
    }

    .center {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 1000px;
    }
  </style>

    <div class="flex flex-row-reverse">
      <span class="font-gothic">
        <% if signed_in? %>
          Signed in as: <%= current_user.email %>
        <%= button_to "Sign out", sign_out_path, method: :delete %>
        <% else %>
          <%= link_to "Sign in", sign_in_path %>
        <% end %>
      </span>
    </div>
    <div class="center">
      <div class="stage" style="width: 360px; height: 360px;">
        <div class="cubespinner font-gothic">
          <div class="face1">Iguana</div>
          <div class="face2">Helium</div>
          <div class="face3">Cube</div>
          <div class="face4">Iguana</div>
          <div class="face5">Helium</div>
          <div class="face6">Cube</div>
        </div>
      </div>
  </div>